### ISSUE TITLE
Unit Testing for the code

### ISSUE THREAD

**Issue by jdha** [NOC-MSM/PyNEMO#10]
Write a series of unit / benchmarking tests to check updates do not break break the code and performance is not hindered.

Unit tests:
e.g. set all temperatures = 25, salinity = 35 to check interpolation

Benchmarking:
Simple AMM7 tests (with standard results on a thredds server) to check updates haven't broken the code

Need to come up with a list.

**Comment by jdha** [comment]
Test list:
- time interpolation
- vertical interpolation 
- volume correction

**Comment by jdha** [comment]
also add one for interpolation across the east-west wrap

**Comment by thopri** [comment]
Basic testing is implemented, I now need to add more tests as listed above. 
Currently just constant in and checked to be constant out for each parameter.

**Comment by thopri** [comment]
Closing this as basic infrastructure is in place, meeting milestone 0.1. more tests will be added as required.
