### ISSUE TITLE
Implement Generic Tidal Module to PyNEMO

### ISSUE THREAD

**Issue by jdha** [NOC-MSM/PyNEMO#22]

**Comment by jdha** [comment]
Big development - create a branch and test before merging back into Master

**Comment by jpolton** [comment]
I'm eager to test it!

**Comment by thopri** [comment]
This is implemented for FES and TPXO, currently need to fix issues with different rim width numbers. Only rim width of 1 works currently. Testing of output needs to be completed as well.

**Comment by thopri** [comment]
Rim width fix implemented, benchmark test is timing out but its not clear if its my local internet connection the THREDDS server or PyNEMO itself. Have created a new issue to cover it.
