### ISSUE TITLE
Using NCML reader with short netcdf variables (enhanced = 'none')

### ISSUE THREAD

**Issue by thopri** [NOC-MSM/PyNEMO#36]
Issue with reading ncml file comprising of CMEMS data, if the underlying netcdf has short variables. This results in a int array being passed and PyNEMO crashing. 

It is unclear if PyJinius and java are reading in enhanced mode, this is documented as being enabled by default and should be able to read the short variable format automatically (use scale factor, offset etc).

This can be explicitly defined in the ncml file, but the fix for the moment is to explicitly define the array as float when it is converted from JavaArray to numpy array. (NCML.py line 229)

**Comment by jdha** [comment]
For ref:

> The preferred way to open a NetcdfFile is through the **_NetcdfDataset.openFile_** factory method...

> When you want the Netcdf-Java library to deal with missing values and scale/offset unpacking, and to identify Coordinate Systems, you should use the _**NetcdfDataset.openDataset**_ factory call ...

PyNEMO currently uses NetcdfDataset.openFile - so we should be ok
