### ISSUE TITLE
Design testing regime

### ISSUE THREAD

**Issue by thopri** [NOC-MSM/PyNEMO#44]
At the moment there is no clear testing cycle with PyNEMO, new bits of code are tested but the impact on old functionality is not fully checked. Long term using Travis CI to test when building will be implemented but for now a testing check list and python script will be created.

The check list will check certain functions or "routes" through  the module, test the GUI and settings editor works etc. The script will test the output, such as confirming constant temp and salinity results in constant temp and salinity out. 

These tests and checklists will be used before each release and merge into master.

**Comment by jdha** [comment]
This is an extension to Task #10

**Comment by thopri** [comment]
So Unit testing has been implemented, now need to add more tests, so far tests only consist of checking constant values in, result in constant values out. There is a list of stuff in task 10 to use as a starting point.
