### ISSUE TITLE
Pynemo can't find bathymetry

### ISSUE THREAD

**Issue by jenjar93** [NOC-MSM/PyNEMO#63]
@thopri Hi Tom, I'm currently trying to run pynemo (IMMERSE branch) but am getting a persistent error very early on that says it can't find the Bathymetry variable - despite that the variable exists in bathy_meter.nc file. Originally I thought it was a mask issue but it still fails both with/without bdy_mask.nc. Any ideas? We've run it with two domains that both worked with a previous version of pynemo: one of these examples, including the nrct.log, can be found on livljobs at /projectsa/accord/SANH_jenjar/CMEMS_SANH/TEST_pynemo3 

Thanks!
Jenny

**Comment by thopri** [comment]
Hi Jenny,

unfortunate I don't have access to the accord folder on projectsa. can you send me the log file? Hopefully its a simple issue!

Many Thanks

Tom


Dr Thomas Prime
Applied Modeller
Marine Data Products Team
UK National Oceanography Centre, European Way, Southampton SO14 3ZH

E:  thopri@noc.ac.uk<mailto:thopri@noc.ac.uk>
noc.ac.uk<http://noc.ac.uk/> | @NOCnews<https://twitter.com/nocnews> | Subscribe to NOCmail e-alerts<https://public.govdelivery.com/accounts/UKNOC/subscriber/new>


DISCLAIMER:  This communication (including any attachments) is intended for the addressee only and may contain confidential, privileged or copyright material. It may not be relied upon or disclosed to any other person without the consent of the National Oceanography Centre. In the event that this communication has incorrectly been addressed to you, it is likewise subject to protection under confidentiality and should not be disclosed.  In either event if you have received this communication in error, please permanently delete it from your system and promptly notify the sender. You should not copy it or use it for any purpose nor disclose or distribute its contents to any other person.


________________________________

**Comment by jenjar93** [comment]
Hi Tom

No problem, please find attached the log file and a screenshot of the command line errors that pop up.

Thanks
Jenny

**Comment by thopri** [comment]
This is due to the NC file being used not having a units attribute for the bathy variable. Without it it makes the program crash. Adding this attribute should fix the problem.  I will also amend the code so that it will log a warning instead of crashing.
