### ISSUE TITLE
Code not processing 2D variables

### ISSUE THREAD

**Issue by jdha** [NOC-MSM/PyNEMO#67]
SSH not extracted: 

Incomplete code in the reformatted profile.py says it all:

    # Idenitify number of boundary points
   
    nbdy = {}
   
    for grd in ['t', 'u', 'v']:
        nbdy[grd] = len(bdy_ind[grd].bdy_i[:, 0])

    # Gather grid information
   
    # TODO: insert some logic here to account for 2D or 3D src_zgr

originally NRCT code from BitBucket looked like this:

# number of points
    num_bdy = {}
    num_bdy['t'] = len(grid_t.bdy_i[:, 0])
    num_bdy['z'] = len(grid_t.bdy_i[bdy_r == 0, 0])
    num_bdy['u'] = len(grid_u.bdy_i[:, 0])
    num_bdy['v'] = len(grid_v.bdy_i[:, 0])

Need to look at the logic in the extract script and try and work out what's missing.

**Comment by thopri** [comment]
This has been fixed for release 0.2.0 code now extracts 2D SSH from source boundary data and interpolates onto NEMO boundary. https://github.com/NOC-MSM/PyNEMO/commit/21e9a431004105c356123a8be9411b4af76a6103
