### ISSUE TITLE
Legacy code not supported: cannot import name 'utime' from 'cftime'

### ISSUE THREAD

**Issue by jpolton** [NOC-MSM/PyNEMO#68]
`cftime` dropped `utime` _after_ 1.4.1. I think that the version is chosen by netcdf4. I only had a problem installing on livljobs8, not on archer2. As a fix I've added `cftime=1.4.1` to the `pynemo_37.yml` file

`utime` appears in:
```
reader/directory.py:from cftime import utime 
reader/ncml.py:from cftime import utime 
```

**Comment by jdha** [comment]
this is also in pynemo_39.yml. @jpolton I guess we can close this ticket?
