### ISSUE TITLE
Testing the master branch: issues with build/install livljobs8 & archer2

### ISSUE THREAD

**Issue by jpolton** [NOC-MSM/PyNEMO#72]
PyNEMO (master) not building on livljobs8 (had the same problem on archer2). Tried a number of things e.g, IMMERSE branch yml file; not specifying offending package versions. No joy.

Possibly need to update `pynemo_37.yaml` dependencies from a working version.

```
livljobs8 PyNEMO $ conda env create -f pynemo_37.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libgfortran=3.0.1

livljobs8 PyNEMO $ module avail anaconda
Rebuilding cache, please wait ... (written to file) done.

----------------------- /packages/lmod/modulefiles/Core ------------------------
   anaconda/3-2.1.0    anaconda/3-5.1.0            anaconda/5-2021
   anaconda/3-4.3.0    anaconda/3-2018_12 (L,D)

  Where:
   D:  Default Module
   L:  Module is loaded
```

**Comment by jpolton** [comment]
Update,  on A2 I fiddled with the `yml` file (starting from IMMERSE branch yml) but then got stuck with the install not completing.

**Comment by jpolton** [comment]
Maybe it is a anaconda module problem. Update to the latest:

```
livljobs8 PyNEMO $ module load anaconda/5-2021
livljobs8 PyNEMO $ conda env create -f pynemo_37.yml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/work/jelt/conda-env/pynemo3_immerse/bin/python', '-m', 'pip', 'install', '-U', '-r', '/login/jelt/PyNEMO/condaenv.nrq9dejj.requirements.txt']
Pip subprocess output:

Pip subprocess error:
/work/jelt/conda-env/pynemo3_immerse/.tmputfqfiy8: line 3: /work/jelt/conda-env/pynemo3_immerse/bin/python: Permission denied

failed

CondaEnvException: Pip failed

livljobs8 PyNEMO $ 
```

Bah!

**Comment by jdha** [comment]
I have a build on livljobs - I'll update on Friday

**Comment by jpolton** [comment]
> Update, on A2 I fiddled with the `yml` file (starting from IMMERSE branch yml) but then got stuck with the install not completing.
> 
> This error (replicated and copied from local machine)
> 
> ```
> error: could not create '/Users/jeff/opt/anaconda3/envs/pynemo3/share/proj/epsg': File exists
> ```


A naive removing offending of the offending ``epsg`` reference in ``setup.py`` allows the install to complete, but then the ``pynemo -h`` falls over

```
less setup.py
...
      #data_files=[(path.join(environ['CONDA_PREFIX'], 'share/proj/epsg'), ['pynemo/share/epsg'])],
      data_files=[],
...
```
Now `pynemo` installs, but
```
> pynemo -h
....
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'
```

**Comment by jpolton** [comment]
> I have a build on livljobs - I'll update on Friday

Hoped I could have saved you the bother. FYI created a draft Pull Request to compare IMMERSE with master branches. Among other edits Tom has done a lot of documentation writing.

**Comment by jdha** [comment]
Quick test on JASMIN with an updated YML file (see pynemo_39.yml) seems to build and install with the addition of:
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/

**Comment by jdha** [comment]
Build and install using the updated YML looks ok on ARCHER2 also. No need to set a JAVA path as it's in the ENV by default. 

I will transfer the test suite data tomorrow and find out how broken the master is then

**Comment by jdha** [comment]
Build and install using the updated YML looks ok on LIVLJOBS* also. Transferred benchmark data to JASMIN/ARCHER/LIVLJOBS*, ran basic test with pynemo -s namelist_local.bdy on livljobs7 and received two output files:
coordinates.bdy.nc  NNA_R12_bdyT_y1979m11.nc
in 20 seconds .... it's a start!

**Comment by jpolton** [comment]
Built/installed on ARCHER2 and local machine with `pynemo_39.yml`. Couldn't get livljobs8 to work with system anaconda module (anaconda/5-2021). I imagine it works fine with a local miniconda install, but didn't want to go there today.

**For reference:**


On mac:

    git clone https://github.com/NOC-MSM/PyNEMO.git

    cd PyNEMO
    git checkout master

    conda env remove --name pynemo
    conda env create -f pynemo_39.yml
    conda activate pynemo

    setenv JAVA_HOME /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home

    python setup.py clean --all
    python setup.py build
    setenv PYTHONPATH /Users/$USER/opt/anaconda3/envs/pynemo/lib/python3.9/site-packages
    python setup.py install

Verify it works:

    pynemo -h

(NB it takes a few minutes for the path to update and the command to be findable)

On ARCHER2:

    cd /work/n01/n01/$USER
    git clone https://github.com/NOC-MSM/PyNEMO.git

    cd PyNEMO
    git checkout master
    #conda env remove --name pynemo
    conda env create -f pynemo_39.yml
    conda activate pynemo

    #export JAVA_HOME=/usr/lib64/jvm/java  # Already set, but in the past has not being set has caused trouble.

    python setup.py clean --all
    python setup.py build
    export PYTHONPATH=/work/n01/n01/$USER/miniconda3/envs/pynemo/lib/python3.9/site-packages:$PYTHONPATH
    python setup.py install

Verify it works:

    pynemo -h

**Comment by jdha** [comment]
Tested and verified on JASMIN too. Produced BDY output as with livljobs*

**Comment by jasontempestholt** [comment]
module load  anaconda/5-2021
livljobs6:~/work/Git/PyNEMO>conda env create -f pynemo_39.yml

fails with permission error on PIP part
---
module load  anaconda/3-2018_12
livljobs7:~/work/Git/PyNEMO>conda env create -f pynemo_39.yml

succeeds !

**Comment by jasontempestholt** [comment]
@jpolton or @jdha 
any tipps on the JAVA location on livjobs7 ?

**Comment by jdha** [comment]
> @jpolton or @jdha
> any tipps on the JAVA location on livjobs7 ?

I haven't actually used JAVA on libljobs yet as the benchmark files are local so make use of python-netcdf4

you have a choice:

/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.171-2.6.13.2.el7.x86_64/jre
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64/jre
/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.191-2.6.15.4.el7_5.x86_64/jre
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-1.el7_9.x86_64/jre
/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.el7_8.x86_64/jre

**Comment by vleguenn** [comment]
Testing the above information to build/install Pynemo Master branch on livljobs7. 

On Livljobs7:
```
cd /work/$USER
mkdir MASTER_PYNEMO
cd MASTER_PYNEMO
git clone https://github.com/NOC-MSM/PyNEMO.git

module load anaconda/3-2018_12
conda env create -f pynemo_39.yml
source activate pynemo

export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-1.el7_9.x86_64/

python setup.py build
export PYTHONPATH=/work/valegu/valegu-conda/pynemo/lib/python3.9/site-packages:$PYTHONPATH
python setup.py install --prefix /work/valegu/valegu-conda/pynemo
```
Build and Install OK. Then I tried : 

`pynemo -h`

![2022-01-17 11_23_28-Window](https://user-images.githubusercontent.com/30412310/149752244-f43269c2-166f-4051-971d-7fe786031564.png)

Next -> try with good namelist for EAFRICA region.
