### ISSUE TITLE
Benchmarking data is not accessible

### ISSUE THREAD

**Issue by nickheavens-cgg** [NOC-MSM/PyNEMO#96]
The link provided to the benchmarking data is not accessible:
https://gws-access.jasmin.ac.uk/public/jmmp_collab/benchmark/

I get:
> Forbidden

> You don't have permission to access /public/jmmp_collab/benchmark/ on this server.

**Comment by jdha** [comment]
Unfortunately that access point was shut down a few weeks ago and I forgot to update the README.
The new location is here:
https://gws-access.jasmin.ac.uk/public/jmmp/benchmark/

**Comment by nickheavens-cgg** [comment]
Thanks!! Nick

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jdha** [comment]
TODO: 

- [ ] update benchmark link in README
- [ ] remove references to the THREDDS server and remote benchmarking
